# Generated by Django 6.0.4 on 2026-04-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('telegram_id', models.BigIntegerField(verbose_name='Telegram ID')),
                ('code', models.CharField(max_length=4, verbose_name='OTP kod')),
                ('user_role', models.CharField(choices=[('PLAYER', 'Futbolchi'), ('OWNER', 'Maydon egasi')], max_length=10, verbose_name='Foydalanuvchi roli')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name="To'liq ism")),
                ('telegram_username', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram username')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('attempts', models.IntegerField(default=0, verbose_name='Urinishlar soni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('expires_at', models.DateTimeField(verbose_name='Amal qilish muddati')),
            ],
            options={
                'verbose_name': 'OTP Kod',
                'verbose_name_plural': 'OTP Kodlar',
                'ordering': ['-created_at'],
                'unique_together': {('phone_number', 'telegram_id')},
            },
        ),
    ]
