# Generated by Django 6.0.4 on 2026-04-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='magictoken',
            name='max_usage',
            field=models.IntegerField(default=10, verbose_name='Maksimal ishlatish soni'),
        ),
        migrations.AddField(
            model_name='magictoken',
            name='usage_count',
            field=models.IntegerField(default=0, verbose_name='Ishlatilish soni'),
        ),
    ]
