# Generated by Django 6.0.4 on 2026-04-25 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_options_booking_slot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('online', 'Online (foydalanuvchi)'), ('manual', "Qo'lda (admin)")], default='online', max_length=10, verbose_name='Bron turi'),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Mijoz ismi (qo'lda)"),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Mijoz telefoni (qo'lda)"),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
    ]
