# Generated by Django 4.2.13 on 2026-04-24 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FootballField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('opening_time', models.TimeField(help_text='e.g. 08:00')),
                ('closing_time', models.TimeField(help_text='e.g. 22:00')),
                ('is_active', models.BooleanField(default=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='fields/covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Football Field',
                'verbose_name_plural': 'Football Fields',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fields/images/')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fields.footballfield')),
            ],
            options={
                'verbose_name': 'Field Image',
                'verbose_name_plural': 'Field Images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Kiyinish xonasi, Parking', max_length=100)),
                ('icon', models.CharField(blank=True, help_text='Icon name or emoji', max_length=50)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='fields.footballfield')),
            ],
            options={
                'verbose_name': 'Field Amenity',
                'verbose_name_plural': 'Field Amenities',
                'ordering': ['name'],
            },
        ),
    ]
