# Generated by Django 6.0.4 on 2026-04-25 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldamenity',
            options={'ordering': ['name'], 'verbose_name': 'Qulaylik', 'verbose_name_plural': 'Qulayliklar'},
        ),
        migrations.AlterModelOptions(
            name='fieldimage',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Maydon rasmi', 'verbose_name_plural': 'Maydon rasmlari'},
        ),
        migrations.AlterModelOptions(
            name='footballfield',
            options={'ordering': ['-created_at'], 'verbose_name': 'Futbol maydoni', 'verbose_name_plural': 'Futbol maydonlari'},
        ),
        migrations.AddField(
            model_name='footballfield',
            name='advance_booking_days',
            field=models.PositiveIntegerField(default=1, help_text='Foydalanuvchi necha kun oldindan bron qila oladi (1, 3, 7...)', verbose_name='Oldindan bron qilish (kun)'),
        ),
        migrations.AddField(
            model_name='footballfield',
            name='is_subscription_active',
            field=models.BooleanField(default=True, verbose_name='Obuna faol'),
        ),
        migrations.AddField(
            model_name='footballfield',
            name='location_url',
            field=models.URLField(blank=True, null=True, verbose_name='Joylashuv (Google Maps URL)'),
        ),
        migrations.AddField(
            model_name='footballfield',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_fields', to=settings.AUTH_USER_MODEL, verbose_name='Egasi (admin)'),
        ),
        migrations.AddField(
            model_name='footballfield',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon raqami'),
        ),
        migrations.AddField(
            model_name='footballfield',
            name='subscription_end',
            field=models.DateField(blank=True, null=True, verbose_name='Obuna tugash sanasi'),
        ),
        migrations.AddField(
            model_name='footballfield',
            name='subscription_start',
            field=models.DateField(blank=True, null=True, verbose_name='Obuna boshlanish sanasi'),
        ),
        migrations.AlterField(
            model_name='fieldamenity',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='fields.footballfield', verbose_name='Maydon'),
        ),
        migrations.AlterField(
            model_name='fieldamenity',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon nomi yoki emoji', max_length=50, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='fieldamenity',
            name='name',
            field=models.CharField(help_text='e.g. Kiyinish xonasi, Parking', max_length=100, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='fieldimage',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fields.footballfield', verbose_name='Maydon'),
        ),
        migrations.AlterField(
            model_name='fieldimage',
            name='image',
            field=models.ImageField(upload_to='fields/images/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='fieldimage',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='footballfield',
            name='address',
            field=models.CharField(max_length=300, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='footballfield',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Shahar'),
        ),
        migrations.AlterField(
            model_name='footballfield',
            name='closing_time',
            field=models.TimeField(help_text='e.g. 02:00', verbose_name='Yopilish vaqti'),
        ),
        migrations.AlterField(
            model_name='footballfield',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='fields/covers/', verbose_name='Muqova rasmi'),
        ),
        migrations.AlterField(
            model_name='footballfield',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan'),
        ),
        migrations.AlterField(
            model_name='footballfield',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='footballfield',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='footballfield',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='footballfield',
            name='opening_time',
            field=models.TimeField(help_text='e.g. 08:00', verbose_name='Ochilish vaqti'),
        ),
        migrations.AlterField(
            model_name='footballfield',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narx (soatiga)'),
        ),
        migrations.AlterField(
            model_name='footballfield',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan'),
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('start_time', models.TimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.TimeField(verbose_name='Tugash vaqti')),
                ('is_active', models.BooleanField(default=True, help_text="Admin bu slotni o'chirib qo'yishi mumkin", verbose_name='Faol')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Band')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='fields.footballfield', verbose_name='Maydon')),
            ],
            options={
                'verbose_name': 'Vaqt sloti',
                'verbose_name_plural': 'Vaqt slotlari',
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['field', 'date', 'is_active', 'is_booked'], name='fields_time_field_i_34114f_idx')],
                'unique_together': {('field', 'date', 'start_time')},
            },
        ),
    ]
