# Generated by Django 6.0.4 on 2026-04-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_alter_fieldamenity_options_alter_fieldimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballfield',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Masalan: 41.311151', max_digits=9, null=True, verbose_name='Kenglik (Latitude)'),
        ),
        migrations.AddField(
            model_name='footballfield',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Masalan: 69.279737', max_digits=9, null=True, verbose_name='Uzunlik (Longitude)'),
        ),
    ]
