# Generated by Django 6.0.4 on 2026-04-29 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0003_footballfield_latitude_footballfield_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballfield',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_role': 'OWNER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_fields', to=settings.AUTH_USER_MODEL, verbose_name='Egasi (admin)'),
        ),
    ]
